### ISSUE TITLE
Looks good, but ... how do we use it?

### ISSUE THREAD

**Issue by halojoy** [Nozemi/SlickBoardLib#8]
I can not find any start page to the forum.
Usually in a framework there is folder 'public' with an index.php
Can you inform me?
Your code looks very promising.

**Comment by Nozemi** [comment]
It's a work in progress. I'm sorry for the inconvenience. The documentation is very lacking at the moment, as things can still potentially change a lot. However, this is simply just the backend, which is a composer package.

Check this https://github.com/Nozemi/Slick-Board for the frontend. This is a work in progress, and there is still lots of things that needs to be done on this.

You can follow the progress of the repositories. I'm currently a full time web developer, so it's not every day I feel like working on private projects.

Anyway, thanks for your interest in my project!
